### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by reed-cj** [SES-5215-F2020/creed1-quant#2]
[[quant]assignment2_fin](https://ses-5215-f2020.github.io/creed1-quant/[quant]assignment2_fin) is technicallly my submission for Assignment 2. I say "technically" because I ran into an issue with all of my knitr code chunks for my four categorical variables which required me to remove those code chunks entirely in order to get my assignment submitted in time. I was able to fix it after class today, and the fixed file is [[quant]assignment2_fixed](https://ses-5215-f2020.github.io/creed1-quant/[quant]assignment2_fixed). But - again - it was submitted a few hours late.

**Comment by saratepfer** [comment]
Nice job on this! I reviewed [quant]assignment2_fixed. Please see a few comments, below.

- I agree that it might make sense to use mutate() to organize your gross rent as a proportion of household income into bins. Or perhaps make two graphs, one with the non-renters (0 values) taken out and one with them included. Similarly for the OCPIP variable.
- Rather than showing the N/A proportion/95% CI in the ACR and TEN tables, I would filter out the "bb" code (which corresponds to N/A, I believe)
- Make sure your caption for your BLD table is accurate. (looks like copy/paste from the previous table.)
