### ISSUE TITLE
Assignment 5 Submission

### ISSUE THREAD

**Issue by reed-cj** [SES-5215-F2020/creed1-quant#5]
Link [here](https://ses-5215-f2020.github.io/creed1-quant/[quant]assignment5)

**Comment by c-voulgaris** [comment]
That code-folding feature in the YAML header is cool.

Some comments on your code (I'm using base R rather than tidyverse because you seem to prefer it):

Lines 83 - 86: A better way to remove observations from your sample is actually remove them your sample. Here's how you would do that:

```
hh_data_mod2 <- hh_data_mod[hh_data_mod$NPPB != "Inf",]
hh_data_mod2 <- hh_data_mod[hh_data_mod$HINCP > 0,]
hh_data_mod2 <- hh_data_mod[hh_data_mod$NPPB > 0,]
hh_data_mod2 <- hh_data_mod[hh_data_mod$BDSP > 0,]
```
Note that the last line in the above chunk should make the first line unnecessary, since the "Inf" values come from dividing by zero when you calculate the number of people per bedroom. So if you remove all the zero-bedroom homes, you'll be eliminating those as well. It might make sense to treat zero-bedroom homes as one-bedroom homes for your purposes though. Something to consider.

Models 2 and 3 aren't actually different models, and I wouldn't even say their using different variables - they're just changing your sample. It doesn't make sense to compare the R-square values. R-squared is the percent of the variation your model explains, but when you change the sample, you're changing the amount of variation that could be explained.

You can't actually use linear regression to predict a categorical variable; you would need to do a logistic regression for that. To run your models as logistic regressions, you'd only need to make some pretty minor modifications to your code though. Here's how you would do it:

Add the following line after line 73 to convert access from a numeric variable to a logical (TRUE/FALSE) variable.

```
hh_data_mod$ACCESS <- as.logical(hh_data_mod$ACCESS)
```

Replace lines 96 and 97 with:
```
model2 <- glm(ACCESS ~ HINCP2 + NPPB2 + struct_type,
            data = hh_data_mod, family = "binomial")
```

I'm suggesting you remove models 2 and 3 entirely - just make a decision about what your sample will be at the outset and keep it consistent for all model alternatives.

Replace lines 131 and 132 with:

```
model4 <- glm(ACCESS ~ HPIP + NP + struct_type,
            data = hh_data_mod, family = "binomial")
```

Replace lines 143 and 144 with:

```
model5 <- glm(ACCESS ~ log(HINCP2) + NP + struct_type + log(HINCP2):struct_type,
            data = hh_data_mod, family = "binomial")
```
A few notes about interpreting logistic regression:

For logistic regression, you don't get an R-squared value, but you do get an AIC value, which is a good measure of model fit. Lower AIC values are better, but other than that, they have no real-world meaning. Just that lower values indicate a better-fitting model.

On interpreting the coefficients in a logistic regression:

Logistic regression predicts the log-odds of an outcome, which is the log of the odds ratio. 

For instance, if something has a 33% probability, the odds of it happening are 1 to 2 (you expect it to happen one time for every two times it doesn't happen), which you can also write as or 1/2 or 0.5, and the log-odds is the log of 0.5, or log(0.5) or -0.3. If it has a 75% probability, the odds are 3 to 1, or 3/1 or 3.0, and the log-odds is the log of 3, or log(3) or 0.48. 

When the odds are greater than 1, the outcome is more likely than not and the log-odds will be positive. When the odds are less than 1, the outcome has a probability less than 50%, and the log-odds will by negative. 

So when the coefficient in a logistic regression is not significant, it means we can't say with 95% confidence which of the two possible outcomes is more likely.

Most people tend to think in terms of probabilities (the percent likelihood that something will happen) rather than in terms of odds (unless they are gamblers - gambling is one area where odds are used pretty commonly), and thinking in terms of log-odds is even less intuitive, so even for a pretty savvy reader, you need to do a little extra work interpreting coefficients for a logistic regression.

The jtools and interaction packages that I demonstrate in the tutorial for this week are actually super helpful for this - when you create one of those interaction charts for a logistic regression, the default setting is for it to convert all the log-odds values to probabilities.

If you're just interpreting coefficients from the table without visualizing them, the best you can really do is say whether they're significant or not and whether they are positive or negative.
